- id: doi:10.4271/2014-01-1781
  remove: true

- id: doi:10.4271/2014-01-1776
  remove: true

- id: doi:10.1007/s11249-018-1016-z
  remove: true

- id: isbn:9780791887219
  remove: true

- type: patent
  title: "Management of actuator dynamics in a multiple actuator hard disk drive with an unequal number of heads on the two outer arms of each actuator"
  patent-number: "US11348607B1"
  author:
    - Manoj Keshavan
    - Siddhesh Vivek Sakhalkar
    - Hitoshi Shindo
  issued: "2022-05-31"
  url: "https://patents.google.com/patent/US11348607B1/en"
